### ISSUE TITLE
[AppImage] v18.2.0.glibc2.17 does not work on Debian Stretch 9.3

### ISSUE THREAD

**Issue by KurtPfeifle** [KmolYuan/Pyslvs-PyQt5#11]
I downloaded the most recent release, pyslvs-18.2.0.glibc2.17-x86_64.AppImage. It does not work on Debian Stretch 9.3.

```
$> ./pyslvs-18.2.0.glibc2.17-x86_64.AppImage 

Traceback (most recent call last):
  File "/tmp/.mount_J3kT0G/usr/bin/pyslvs", line 6, in <module>
    from core import *
  File "/tmp/.mount_J3kT0G/usr/bin/core/__init__.py", line 10, in <module>
    from .info import *
  File "/tmp/.mount_J3kT0G/usr/bin/core/info/__init__.py", line 9, in <module>
    from .info import (
  File "/tmp/.mount_J3kT0G/usr/bin/core/info/info.py", line 23, in <module>
    import requests
  File "/tmp/.mount_J3kT0G/usr/lib/python3.5/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/tmp/.mount_J3kT0G/usr/lib/python3.5/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/tmp/.mount_J3kT0G/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/tmp/.mount_J3kT0G/usr/lib/python3.5/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
  File "/tmp/.mount_J3kT0G/usr/lib/python3.5/site-packages/urllib3/packages/__init__.py", line 3, in <module>
    from . import ssl_match_hostname
  File "/tmp/.mount_J3kT0G/usr/lib/python3.5/site-packages/urllib3/packages/ssl_match_hostname/__init__.py", line 9, in <module>
    from ssl import CertificateError, match_hostname
  File "/usr/lib/python3.5/ssl.py", line 135, in <module>
    PROTOCOL_SSLv23 = _SSLMethod.PROTOCOL_SSLv23 = _SSLMethod.PROTOCOL_TLS
  File "/usr/lib/python3.5/enum.py", line 274, in __getattr__
    raise AttributeError(name) from None
AttributeError: PROTOCOL_TLS
```

Maybe you want to reach out to the [IRC channel #AppImage on Freenode](https://webchat.freenode.net/?channels=appimage). There you'll find AppImage developers who are willing to help fix any problems you may have with packaging and testing your AppImage.

**Comment by KmolYuan** [comment]
Maybe the problem is cause from https://github.com/pypa/virtualenv/issues/818.

I will make package amendments as soon as possible.

**Comment by KurtPfeifle** [comment]
Thanks, @KmolYuan, that was fast.

I'll now download the new AppImage and test it again.

**Comment by KurtPfeifle** [comment]
It's a different error message now:

````
$>  ./pyslvs-18.2.0.glibc2.17-x86_64.AppImage 

Traceback (most recent call last):
  File "/tmp/.mount_KEC451/usr/bin/pyslvs", line 6, in <module>
    from core import *
  File "/tmp/.mount_KEC451/usr/bin/core/__init__.py", line 10, in <module>
    from .info import *
  File "/tmp/.mount_KEC451/usr/bin/core/info/__init__.py", line 9, in <module>
    from .info import (
  File "/tmp/.mount_KEC451/usr/bin/core/info/info.py", line 25, in <module>
    from PyQt5.QtCore import qVersion, PYQT_VERSION_STR
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1113, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1225, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1264, in _fill_cache
OSError: [Errno 5] Input/output error: '/tmp/.mount_KEC451/usr/lib/python3.5/site-packages/PyQt5'
````

Also, I noted that the size of the AppImage now is only 116.406.836 Bytes. The previous build had 226.164.736 Bytes.

**Comment by KmolYuan** [comment]
Well, I'm trying to build the executable release on Travis CI, `.app` are successful but the AppImage is not looking good.

If there has a good way to build a PyQt-AppImage projects on Travis CI, the problem will not dependent on my PC environment.

**Comment by Symbian9** [comment]
> If there has a good way to build a PyQt-AppImage projects on Travis CI, the problem will not dependent on my PC environment.

Think, for answer on this question need ask @probonopd (AppImage dev)

**Comment by probonopd** [comment]
Simple, please build on Ubuntu 14.04 (trusty) rather than on newer versions. This way the application inside the AppImage will not have dependencies on a glib that is "too new".

**Comment by KmolYuan** [comment]
@probonopd The AppImage that build from Travis CI currently has some trouble.

The package is created in virtualenv but Python is installed at `/opt` of Travis CI (xenial Python 3.7).

+ Internal Python cannot find `libpython3.7m.so` since it is be located at `opt/python/3.7.0/lib`, which should be placed at `usr/lib/x86_64-linux-gnu`.

+ `usr/lib/python3.7/platform.py` is missing.

```
pyslvs.AppImage
|-- opt/python/3.7.0/lib
|-- usr
  |-- bin
  |-- lib
  | |-- python3.7
  | |-- x86_64-linux-gnu
  |-- lib64 (empty)
  |-- share (NetworkX doc only)
```

**Comment by probonopd** [comment]
xenial Python is not good for an AppImage, because it would only run on xenial and later, whereas currently trusty and above are still supported versions. So please bundle trusty Python.

**Comment by KmolYuan** [comment]
@probonopd Same issue from trusty environment (https://github.com/KmolYuan/Pyslvs-PyQt5/blob/master/.travis.yml#L6) and the current AppImage release (https://github.com/KmolYuan/Pyslvs-PyQt5/releases/tag/v18.09.1).

**Comment by probonopd** [comment]
@KmolYuan does it work in the `venv` virtual environment you are creating? (Prior to making an AppImage out of it)?

**Comment by probonopd** [comment]
Let's see:

```
me@host:~$ find AppDir/ | grep libpython3.6m.so.1.0
AppDir/opt/python/3.6.3/lib/libpython3.6m.so.1.0
```

That is a bit strange. Shouldn't the virtualenv command have copied it into the virtual environment?

**Comment by KmolYuan** [comment]
It is located normal position when created `venv` by my native Python at `/usr/bin`:

```bash
> virtualenv ./usr --python=python3 --always-copy --verbose
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
```

![default](https://user-images.githubusercontent.com/10264720/47076862-4e615700-d232-11e8-8e28-ad617d952836.png)

But the Python installation of Travis-CI is like this (same as 3.6):

![default](https://user-images.githubusercontent.com/10264720/47077211-05f66900-d233-11e8-93e5-aba72f7d7333.png)

Then it outputs:

```
> bash ./appimage_recipe.sh
Using real prefix '/opt/python/3.6.3'
```

And some libraries or builtin scripts are locate at `opt`.

**Comment by probonopd** [comment]
Interesting, I was not aware of this. What happens if you change

https://github.com/KmolYuan/Pyslvs-PyQt5/blob/7e98b8981d259224ef41d5b768abc90b6718b926/.travis.yml#L2

to `C` and and use `sudo apt -y install python`?

**Comment by KmolYuan** [comment]
Maybe it is not completely independent for Python built-in scripts that environment creation rely on `virtualenv`. PyInstaller will be more better for module import analysis.

The built-in scripts might be copied after environment:

https://github.com/KmolYuan/Pyslvs-PyQt5/blob/f884ab463bef20cf8412824fd5a4ba3b2b25768a/appimage_recipe.sh#L45-L94

The [re-released AppImage](https://github.com/KmolYuan/Pyslvs-PyQt5/releases/tag/v18.09.1) is dependent on Python 3.7. It can finally run on my computer, which has only Python 3.6.
