### ISSUE TITLE
Can't run v0.9.0

### ISSUE THREAD

**Issue by Symbian9** [KmolYuan/Pyslvs-PyQt5#7]
Pyslvs-PyQt5 version: 0.9.0
OS: MX Linux MX-17 (Debian 9 "Stretch"), x86_64 (64-bit)

```
$ ./pyslvs-0.9.0.glibc2.17-x86_64.AppImage
zenity, kdialog, Xdialog missing. Skipping /var/tmp/.mount_bbVPnT/usr/bin//pyslvs.wrapper.
Traceback (most recent call last):
  File "/var/tmp/.mount_bbVPnT/usr/bin/pyslvs", line 6, in <module>
    from core.info.info import INFO, args
  File "/var/tmp/.mount_bbVPnT/usr/bin/core/info/info.py", line 21, in <module>
    import platform
  File "/usr/lib/python3.5/platform.py", line 117, in <module>
    import sys, os, re, subprocess
  File "/usr/lib/python3.5/subprocess.py", line 50, in <module>
    import signal
  File "/usr/lib/python3.5/signal.py", line 3, in <module>
    from functools import wraps as _wraps
  File "/var/tmp/.mount_bbVPnT/usr/lib/python3.5/functools.py", line 23, in <module>
    from weakref import WeakKeyDictionary
  File "/var/tmp/.mount_bbVPnT/usr/lib/python3.5/weakref.py", line 12, in <module>
    from _weakref import (
ImportError: cannot import name '_remove_dead_weakref'
$ 
```

**Comment by KmolYuan** [comment]
Maybe there has some differences between Python libraries?

If the AppImage is not working, other non-Ubuntu platform should install requirements or running in virtual machine.

**Comment by probonopd** [comment]
The AppImage should be made in a way that Python and all of its modules are loaded from within the AppImage. Nothing from the system should be used.
